[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/boards/*"
  to = "/boards/index.html"
  status = 200

[[redirects]]
  from = "/chapter-wise/*"
  to = "/chapter-wise/index.html"
  status = 200

[[redirects]]
  from = "/mock-test/*"
  to = "/mock-test/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
